### ISSUE TITLE
User.stats not returning stats

### ISSUE THREAD

**Issue by AStrangeEnigma** [mattvperry/mumble-ruby#50]
I'm not sure if this is the intended behaviour (?), but if it is I would still like to know how I'm supposed to access that stats of the users.
```
> cli.users
=> {143=>#<Mumble::User session=143 user_id=65 actor=143 name=RubyClient channel_id= hash=bd65fde1547554e9dc877dfe061d39d7b1c0fff3 comment= mute=8 deaf= self_mute=true self_deaf=>, 126=>#<Mumble::User session=126 user_id=62 actor=126 name=brick@work channel_id=0 hash=02fa8fe35ed5c2d9a66b3b908dc968c840d83a0d comment= mute=8 deaf= self_mute=true self_deaf=false>, 144=>#<Mumble::User session=144 user_id=63 actor=144 name=Robocop channel_id= hash=9afd8d66e6622b65fa4fcdf40455632fd0530817 comment=brick.codes mute=8 deaf= self_mute= self_deaf=>}

> cli.users[143].stats
=> 9
```

Sometimes I've seen it return 8 as well. As far as I can tell that stats command doesn't trigger any action, so surely it should return the stats? I could definitely by misunderstanding something, so sorry if that is the case.

Thanks!

**Comment by Ape** [comment]
I have this issue, too.

**Comment by Ape** [comment]
Okay, I found out how this works. ```stats``` will request the data, so you will have to setup a callback. For example:

```ruby
cli.on_user_stats do |stats|
    puts stats
end

cli.me.stats
```

**Comment by AStrangeEnigma** [comment]
Thanks Ape! That's hugely helpful. I agree that this should be documented somewhere, I couldn't find that information anywhere

**Comment by AStrangeEnigma** [comment]
I'll close this issue though because it does work.
